name: CI

on: 
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build-with-gazebo:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
  
    - name: Dependencies
      run: |
        choco install -y wget unzip
        cd C:/
        wget https://github.com/traversaro/robotology-superbuild-dependencies-vcpkg/releases/download/archive/vcpkg-robotology-with-gazebo-deps.zip
        unzip vcpkg-robotology-with-gazebo-deps.zip -d C:/
        rm vcpkg-robotology-with-gazebo-deps.zip
    
    - name: Check free space 
      shell: bash 
      run: |
        df -h
        
    - name: Install required python-based tools
      shell: bash
      run: |
        pip install vcstool colcon-common-extensions
    
    # Based on https://colcon.readthedocs.io/en/released/user/quick-start.html#build-gazebo-and-the-ignition-packages
    - name: Download Gazebo and related libraries
      shell: bash
      run: |
        mkdir C:/robotology/gazebo
        cd C:/robotology/gazebo
        mkdir src
        vcs import src < ${GITHUB_WORKSPACE}/gazebo-repos.yaml
        
    - name: Build Gazebo and related libraries
      shell: bash
      run: |
        cd C:/robotology/gazebo
        colcon build --merge-install --cmake-args -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:/robotology/vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_TESTING:BOOL=OFF
        
    # Remove temporary files
    - name: Cleanup vcpkg temporary directories
      shell: cmd 
      run: |
        RMDIR /Q/S C:\robotology\gazebo\build
        RMDIR /Q/S C:\robotology\gazebo\src
        
    - uses: actions/upload-artifact@v1
      with:
        name: vcpkg-with-gazebo
        path: C:/robotology
        
    - name: Prepare release file
      if: github.event_name == 'release'
      shell: cmd 
      run: |
        7z a vcpkg-robotology-with-gazebo.zip C:\robotology
        
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./vcpkg-robotology-with-gazebo.zip
          asset_name: vcpkg-robotology-with-gazebo.zip
          asset_content_type: application/zip
